
    name: Node.js CI

    on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

    jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
        matrix:
            node-version: [16.x]
            # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
        - uses: actions/checkout@v2

        - name: Use Node.js ${ matrix.node-version }
            uses: actions/setup-node@v2
            with:
            node-version: ${ matrix.node-version }
            cache: "npm"

        - id: get-repo-values
            run: echo "url=https://github.com/gavincaul/gavincaulfield.com.git" >> $GITHUB_OUTPUT

        - name: Update package.json homepage
            uses: jossef/action-set-json-field@v1
            with:
            file: package.json
            field: homepage
            value: ${ steps.get-repo-values.outputs.url }

        - run: npm ci
        - run: npm run test -- --coverage |& tee ./public/test_report.txt
        - run: echo "<html><head><meta http-equiv='refresh' content='0; URL=${github.server_url}/${github.repository}' /></head><body>Redirecting to repository</body></html>" > ./public/github.html
        - run: npm run build --if-present

        - name: Deploy to GitHub Pages
            run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git remote set-url origin https://${ secrets.GITHUB_TOKEN }@github.com/${ github.repository }
            npm run predeploy
            npm run deploy
            env:
            github_token: ${ secrets.GITHUB_TOKEN }
            repository: ${ github.repository }
    